[package]
name = "client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_ui",
    "bevy_text",
    "bevy_gizmos",
    "default_font",
    "bevy_state",
    "bevy_remote",
    "x11",
    "wayland",
] }
shared = { path = "../shared" }
bot_ai = { path = "../bot_ai" }
serde = { workspace = true }
bincode = { workspace = true }
ewebsock = "0.8"
crossbeam-channel = "0.5"



[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { workspace = true, default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "bevy_ui",
    "bevy_text",
    "bevy_gizmos",
    "default_font",
    "bevy_state",
    "webgl2",
] }
getrandom = { version = "0.3", features = ["wasm_js"] }
getrandom_02 = { package = "getrandom", version = "0.2", features = ["js"] }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "Location"] }
