[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
bevy = { workspace = true, default-features = false, features = ["bevy_state", "bevy_remote"] }
shared = { path = "../shared" }
bot_ai = { path = "../bot_ai" }
serde = { workspace = true }
bincode = { workspace = true }
tokio = { version = "1.38", features = ["full"] }
tokio-tungstenite = "0.24"
futures-util = "0.3"
crossbeam-channel = "0.5"

